### ISSUE TITLE
Update developer guide

### ISSUE THREAD

**Issue by pradyuprasad** [AY2425S1-CS2103T-T13-4/tp#30]
# Problem
Current DG is not updated for carelink

# TODO

- [x] Target user profile, value proposition, and user stories: Update the target user profile and value proposition to match the project direction you have selected. Give a list of the user stories (and update/delete existing ones, if applicable), including priorities. This can include user stories considered but will not be included in the final product.
- [x] #39
- [x] Non-functional requirements: Note: Many of the given project constraints can be considered NFRs. You can add more. e.g. performance requirements, usability requirements, scalability requirements, etc.
- [x] Glossary: Define terms that are worth recording.
